language: r
r:
  - oldrel
  - release
  - devel
dist: trusty
sudo: required
r_binary_packages:
  - rasterVis
  - rgdal
  - testthat
  - rmarkdown
r_github_packages:
  - cbig/zdat
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
